sudo: required
dist: bionic
language: cpp

notifications:
  email:
    on_success: change
    on_failure: change

# matrix:
#   include:
    # - compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++
    #   env: COMPILER=g++
    # - compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-5
    #   env: COMPILER=g++-5
    # - compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.6
    #       packages:
    #         - clang-3.6
    #   env: COMPILER=clang++-3.6
    # - compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-precise-3.7
    #       packages:
    #         - clang-3.7
    #   env: COMPILER=clang++-3.7

env:
    global:
        BUILD_ON_TRAVIS=1
        BUILD_DOXYGEN_COMPILE=g++

script:
  - $COMPILER -v
  - mkdir build
  - cd build
  - /opt/cmake/bin/cmake --version
  - /opt/cmake/bin/cmake -DCMAKE_CXX_COMPILER=$COMPILER -DBLUETOE_EXCLUDE_SLOW_TESTS=1 ..
  - make
  - ctest --verbose

after_success:
  - cd $TRAVIS_BUILD_DIR
  # - sudo apt-get install --yes graphviz
  # - ls -la
  # - pwd
  # - doxygen -v
  # - ./publish-doxygen

before_install:
  - sudo apt-get update -qq
  - wget https://github.com/Kitware/CMake/releases/download/v3.19.4/cmake-3.19.4-Linux-x86_64.sh
  - wget https://cmake.org/files/v3.11/cmake-3.11.4-Linux-x86_64.sh
  - mkdir /opt/cmake
  - sh cmake-3.19.4-Linux-x86_64.sh --prefix=/opt/cmake --skip-license
  - wget https://launchpad.net/%7Eboost-latest/+archive/ubuntu/ppa/+files/libboost1.55-dev_1.55.0-1ppa1%7Esaucy1_amd64.deb
  - sudo dpkg --install libboost1.55-dev_1.55.0-1ppa1~saucy1_amd64.deb
  # - openssl aes-256-cbc -K $encrypted_eb6359394db6_key -iv $encrypted_eb6359394db6_iv -in config/travisci_rsa.enc -out config/travisci_rsa -d
